INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Comande o Comandante Shepard e lidere sua equipe em uma saga épica para salvar a galáxia da aniquilação por uma antiga raça de máquinas.', 'Vivencie a lenda do Comandante Shepard nesta aclamada trilogia de RPG de ação. Suas escolhas moldam o destino da galáxia enquanto você recruta uma equipe diversificada, explora planetas distantes e enfrenta os Reapers, uma ameaça colossal determinada a erradicar toda a vida orgânica. Prepare-se para uma narrativa cinematográfica, combate intenso e decisões com consequências duradouras.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Explore um vasto e atmosférico Velho Oeste como Arthur Morgan, um fora da lei lutando contra seus ideais e lealdade à sua gangue.', 'América, 1899. O fim da era do velho oeste começou. Após um assalto dar errado na cidade de Blackwater, Arthur Morgan e a gangue Van der Linde são forçados a fugir. Com agentes federais e os melhores caçadores de recompensas da nação em seu encalço, a gangue precisa roubar, assaltar e lutar para sobreviver no impiedoso coração da América. Enquanto divisões internas ameaçam desmantelar a gangue, Arthur deve fazer uma escolha entre seus próprios ideais e a lealdade à gangue que o criou.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Assuma o papel de Geralt de Rívia, um caçador de monstros profissional, em busca da Criança da Profecia em um mundo aberto vibrante e perigoso.', 'The Witcher 3: Wild Hunt é um RPG de mundo aberto de nova geração com uma história fascinante, ambientado em um universo de fantasia visualmente deslumbrante, cheio de escolhas significativas e consequências impactantes. Como Geralt de Rívia, você embarca em uma jornada épica para encontrar Ciri, a Criança da Profecia, enquanto navega por reinos devastados pela guerra, enfrenta criaturas letais e interage com personagens inesquecíveis.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Domine o combate brutal com espadas e ferramentas prostéticas shinobi como o "lobo de um braço só" em uma missão para resgatar seu jovem mestre no Japão feudal.', 'Em Sekiro: Shadows Die Twice, você é o "lobo de um braço só", um guerreiro desonrado e desfigurado, resgatado da beira da morte. Destinado a proteger um jovem lorde que é descendente de uma linhagem ancestral, você se torna alvo de muitos inimigos cruéis, incluindo o perigoso clã Ashina. Quando o jovem lorde é capturado, nada o deterá em uma jornada perigosa para recuperar sua honra, nem mesmo a própria morte. Explore o Japão Sengoku do final do século XVI, um período brutal de conflitos constantes de vida ou morte, enquanto enfrenta inimigos épicos em um mundo sombrio e distorcido.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2020, 'Role-playing (RPG), Adventure', 'Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Defenda a Ilha de Tsushima dos invasores mongóis como Jin Sakai, um guerreiro samurai forçado a escolher entre a tradição e um novo caminho de luta.', 'No final do século XIII, o império mongol devastou nações inteiras em sua campanha para conquistar o Oriente. A Ilha de Tsushima é tudo o que resta entre o Japão continental e uma enorme frota de invasão mongol. Enquanto a ilha queima após a primeira onda do ataque mongol, o guerreiro samurai Jin Sakai surge como um dos últimos membros sobreviventes de seu clã. Ele está determinado a fazer o que for preciso, a qualquer custo, para proteger seu povo e recuperar seu lar, mesmo que isso signifique deixar de lado as tradições que o moldaram como guerreiro.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Nintendo, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Junte-se a Mario e Yoshi em uma aventura vibrante pela Terra dos Dinossauros para resgatar a Princesa Peach das garras de Bowser!', 'Explore a colorida e mágica Terra dos Dinossauros com Mario e seu novo amigo Yoshi neste clássico atemporal de plataforma. Descubra saídas secretas, power-ups e navegue por níveis desafiadores para frustrar os planos de Bowser e salvar a Princesa Peach. Sua jogabilidade icônica e mundo encantador cativaram jogadores por gerações.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC, Switch', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Desça ao vasto reino interconectado de Hallownest nesta desafiadora e atmosférica aventura de ação Metroidvania.', 'Enfrente as profundezas de um reino esquecido em Hollow Knight, uma épica aventura de ação. Explore cavernas sinuosas, lute contra criaturas corrompidas e faça amizade com insetos bizarros, tudo em um estilo 2D clássico desenhado à mão. Descubra segredos antigos e resolva os mistérios enterrados no coração de Hallownest, um vasto mundo subterrâneo cheio de perigos e maravilhas.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4.0, 2015, 'Platform', 'XBox, Playstation, PC, Switch', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Embarque em uma jornada visualmente deslumbrante e emocionalmente carregada como Ori, um jovem órfão destinado a atos heroicos.', 'Vivencie o aclamado conto de Ori, um jovem espírito, e sua jornada para salvar a floresta moribunda de Nibel. Este jogo de plataforma e ação ostenta uma arte pintada à mão de tirar o fôlego, uma narrativa profundamente emocional e uma jogabilidade meticulosamente elaborada que combina exploração, resolução de quebra-cabeças e sequências de fuga emocionantes. Prepare-se para uma história sobre amor, sacrifício e a esperança que reside em todos nós.');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC, Switch', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Lute em um mundo surreal inspirado nos desenhos animados dos anos 1930 neste clássico jogo de ação run-and-gun focado em batalhas contra chefes.', 'Cuphead é um jogo de ação run-and-gun clássico, fortemente focado em batalhas épicas contra chefes. Inspirado nos desenhos animados da década de 1930, os visuais e o áudio são meticulosamente criados com as mesmas técnicas da época: animação tradicional desenhada à mão, fundos em aquarela e trilhas sonoras originais de jazz. Jogue como Cuphead ou Mugman (em modo individual ou cooperativo local) enquanto atravessa mundos estranhos, adquire novas armas, aprende super movimentos poderosos e descobre segredos ocultos enquanto tenta pagar sua dívida com o diabo!');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4.0, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Corra através do tempo com Sonic the Hedgehog para salvar o Little Planet e Amy Rose das garras do Dr. Robotnik e Metal Sonic!', 'Junte-se a Sonic em uma de suas aventuras mais célebres! O Dr. Robotnik acorrentou o Little Planet a uma montanha e está construindo sua arma suprema: Metal Sonic. Sonic deve usar o poder do Little Planet para viajar através do tempo – passado, presente e futuro – para destruir as máquinas de Robotnik, resgatar Amy Rose e recuperar as Joias do Tempo. Experimente a jogabilidade icônica, visuais vibrantes e uma trilha sonora inesquecível que introduziu Metal Sonic e Amy Rose ao universo Sonic.');